### PR TITLE
Use platform transition in the oci_image_index rule

### PR DESCRIPTION
**Pull request by moroten**
The current way of listing images makes Bazel build images for a platform that is not the configured target platform, defined by --platforms. This commit changes the behaviour and applies a transition so that the images are built for the configured target platform.

New way:
```
oci_image_index(
    name = "app",
    image = ":app_linux",
    platforms = [
        "@io_bazel_rules_go//go/toolchain:linux_amd64",
        "@io_bazel_rules_go//go/toolchain:linux_arm64",
    ]
)
```

Old way:
```
oci_image_index(
    name = "app",
    image = [
        ":app_linux_amd64",
        ":app_linux_arm64"
    ],
)
```

For backwards compatibility, the old way is still possible to use.

### CODE REVIEW

**Comment by alexeagle** [comment]
Our original intent here was to minimize the code in rules_oci that needs to understand what the user is doing, we liked that transitions occur explicitly. OTOH I do see how this syntax sugar makes it nicer.

> Bazel build images for a platform that is not the configured target platform

I'm not sure I follow this existing bug you suggest - don't we build for the same platforms before and after this change? The same targets get transitioned in the same way?

**Comment by moroten** [comment]
> > Bazel build images for a platform that is not the configured target platform
> 
> I'm not sure I follow this existing bug you suggest - don't we build for the same platforms before and after this change? The same targets get transitioned in the same way?

Consider the following example:
```starlark
cc_binary(
    name = "binary_linux_arm64",
)
pkg_tar(
    name = "app_tar_linux_arm64",
    srcs = [":binary_linux_arm64"],
)
oci_image(
    name = "app_image_linux_arm64",
    tars = [":app_tar_linux_arm64"],
)
oci_image_index(
    name = "app_index",
    images = [
        ":app_image_linux_arm64"
    ],
)
```

I would normally only have a target called `binary_linux`. Building `binary_linux_arm64` with `--platforms=//:linux_x86_64` is possible, but makes no sense as the result will be a binary `binary_linux_arm64` will not be compatible with arm64. Adding `target_compatible_with=[...arm64]` will make all `_arm64` targets unbuildable on `x86_64`, which is correct, but `:app` will also become unbuildable.

The idea here is that all the `_linux_arm64` suffixes are removed and that `bazel build :app_image --platforms=//:linux_x86_64` and `bazel build :app_image --platforms=//:linux_arm64` produce images for respective OS, even if my host is Windows.

```starlark
cc_binary(
    name = "binary",
)
pkg_tar(
    name = "app_tar",
    srcs = [":binary"],
)
oci_image(
    name = "app_image",
    tars = [":app_tar"],
)
```

The `app_index` target itself is actually compatible with any target platform, or at least multiple platforms, i.e. I expect to get the same output independent on `--platforms` (e.g. building on Windows or MacOS).

**Comment by thesayyn** [comment]
https://github.com/bazel-contrib/rules_oci/issues/228#issue-1698785947

**Comment by moroten** [comment]
Let's keep the discussion about the plan forward in #228.

Are the failing tests due to this change? My feeling is that it is something unrelated. Anyway, some tests should be added for this new functionality.

**Comment by thesayyn** [comment]
Can we close this since we don't have to land a change for this?

**Comment by thesayyn** [comment]
Okay, i am going to close this for house keeping purposes. Thank you for putting time into this.

**Pull request closed without merging**
