### PR TITLE
feat: include owner label in the history for tars

### PR DESCRIPTION
**Pull request by thesayyn**
Cross-ref https://github.com/google/go-containerregistry/issues/1819

### CODE REVIEW

**Review by alexeagle — APPROVED** [review]

**Comment by alexeagle** [comment]
nit: would be nice to include some form of "demo" of something like dive showing the layers

**Comment by thesayyn** [comment]
Closing this as no longer applicable.

**Comment by alexeagle** [comment]
error reported
```
"ImageLayerFailure: UnsupportedImageLayerDetected - Layer Digest sha256:dd2d1b3af2eef813d8cf22b1e17c4500e6c34fd80eddb0f0a78e80632fc872da"
```
which is hypothesized to be due to rules_oci v2 dropping history that was present in rules_oci v1

```
  "architecture": "amd64",
  "author": "github.com/chainguard-dev/apko",
  "created": "2024-06-28T05:42:58Z",
  "history": [
    {
      "author": "apko",
      "created": "2024-06-28T05:42:58Z",
      "created_by": "apko",
      "comment": "This is an apko single-layer image"
    }
  ],
  "os": "linux",
  "rootfs": {
    "type": "layers",
    "diff_ids": [
      "sha256:8952da8c429f5b89a61500dc9b5e52ce326da208332a8c16f8e51b0563bf53f7",
      "sha256:dd2d1b3af2eef813d8cf22b1e17c4500e6c34fd80eddb0f0a78e80632fc872da",
      "sha256:45aca4f0d57586f6ab7e6c7b9104204b93f02a4afef6e0f5ffaad4ac003440e8"
    ]
  },
vs
  "architecture": "amd64",
  "author": "github.com/chainguard-dev/apko",
  "created": "2024-06-28T05:42:58Z",
  "history": [
    {
      "author": "apko",
      "created": "2024-06-28T05:42:58Z",
      "created_by": "apko",
      "comment": "This is an apko single-layer image"
    },
    {
      "created": "0001-01-01T00:00:00Z"
    },
    {
      "created": "0001-01-01T00:00:00Z"
    }
  ],
  "os": "linux",
  "rootfs": {
    "type": "layers",
    "diff_ids": [
      "sha256:8952da8c429f5b89a61500dc9b5e52ce326da208332a8c16f8e51b0563bf53f7",
      "sha256:dd2d1b3af2eef813d8cf22b1e17c4500e6c34fd80eddb0f0a78e80632fc872da",
      "sha256:45aca4f0d57586f6ab7e6c7b9104204b93f02a4afef6e0f5ffaad4ac003440e8"
    ]
  },
  
```

**Comment by thesayyn** [comment]
Closing in favor of https://github.com/bazel-contrib/rules_oci/pull/654

**Pull request closed without merging**
