### PR TITLE
Updated `image.sh.tpl` and `tarball.sh.tpl` to use hermetic tools.

### PR DESCRIPTION
**Pull request by rickvanprim**
Depends on https://github.com/aspect-build/bazel-lib/pull/721.

### CODE REVIEW

**Review by alexeagle — COMMENTED** [review]
Thanks, this overlaps with https://github.com/bazel-contrib/rules_oci/pull/385 which I haven't landed because it's a breaking change. It looks like this one isn't though - it works with current versions of dependencies.

**Comment by alexeagle** [comment]
Oh I see, it's certainly breaking as it assumes some bazel-lib changes that haven't landed yet.

**Comment by rickvanprim** [comment]
Yes this is dependent on the other PR.  I updated this PR description to reflect that.  What's the policy around updating the version of `aspect_bazel_lib` that `rules_oci` depends on?

**Comment by alexeagle** [comment]
That's where #385 got blocked - unless we backport things to bazel-lib 1.x, we are treating it as a breaking change for rules_oci to require bazel-lib 2.x.

**Comment by rickvanprim** [comment]
I haven't tried, but presumably I could open another PR in `aspect_bazel_lib` against the `1.x` branch, as the changes to add those toolchains are all pretty self contained.

**Comment by thesayyn** [comment]
Now, both oci_image and oci_tarball is using hermetic tools. Closing this.

**Pull request closed without merging**
