### PR TITLE
add OAuth2 support

### PR DESCRIPTION
**Pull request by xbog300**
As per https://github.com/bazel-contrib/rules_oci/issues/129, I implemented `OAuth2` support for `rules_oci`.

A little bit of a background story of the proposed solution:

`OAuth2` requires a `POST` request to be sent. This, unfortunately, cannot be done by the `repository_ctx.download` func.
**Bazel does not provide a way to send a POST request.**

In order to enable `OAuth2` support, a tiny `python` script was added. The entire purpose of the script is to do the `POST` request. In order to do that, a `requests` package was used. 

The support is optional, meaning it's only enabled if `SUPPORT_OAUTH2` env var is being set (appropriate information about the lack of var set is being displayed).

Also, the change I made verifies that the environment in which the rule is being executed, has `python3` binary available, and if the python installed in the environment has `requests` package available, too.

**What are the options?**

It's clear the `POST` request can't be handled by the Bazel itself, meaning we must look for other ways of sending it.
Python is one option, other one is `curl / wget` on `Linux` and `PowerShell` on `Windows`.

Please let me know what are your thoughts on the solution I proposed, to engage `python` in order to enable `OAuth2` support.

### CODE REVIEW

**Comment by thesayyn** [comment]
Thanks for the PR,  there's a lot to be discussed here, I'll do my best reply again this week.

**Comment by xbog300** [comment]
ping @thesayyn

**Comment by thesayyn** [comment]
> In order to enable `OAuth2` support, a tiny `python` script was added. The entire purpose of the script is to do the `POST` request. In order to do that, a `requests` package was used.

Okay, this sounds bad, python dependency is a "no-go" for us. 

> other one is `curl / wget` on `Linux` and `PowerShell` on `Windows`.

This sounds like a better alternative than using a python script.

**Comment by xbog300** [comment]
> Okay, this sounds bad, python dependency is a "no-go" for us.

Affirm, I used python just to create a concept of a potential solution and to prove it works.

Will do the changes.

For `linux`, I think it'd be great to try use `curl` first, and if that's not available in the path (which might be the case), then treat `wget` as a last resort.

For `Windows`, I'll just go with `PowerShell`, which is there by default AFAICS.

**Comment by lukaszwawrzyk** [comment]
@thesayyn @xbog300 I tried to address the comments in https://github.com/bazel-contrib/rules_oci/pull/626

**Comment by thesayyn** [comment]
@xbog300 looks like [lukaszwawrzyk](https://github.com/lukaszwawrzyk) picked up your PR, do you want to close yours as i already left bunch of comments at the other PR?

**Comment by thesayyn** [comment]
closing in favor of https://github.com/bazel-contrib/rules_oci/pull/626

**Pull request closed without merging**
