### PR TITLE
Add labels to oci_image

### PR DESCRIPTION
**Pull request by psalaberria002**
Fixes https://github.com/bazel-contrib/rules_oci/issues/47

I would like to have stamping support before merging this PR. I see @alexeagle is working on stamping in https://github.com/bazel-contrib/rules_oci/pull/70.

From what I understand, the script that builds the image will need to read the volatile and stable files when stamping is enabled, and do variable substitution for each key (if found). Should I try something like https://github.com/aspect-build/bazel-lib/blob/998ee223690ed07b3dfc31738dae839206bd60b0/lib/tests/stamping/stamper.sh ? Or is there a more native alternative for stamping?

### CODE REVIEW

**Comment by psalaberria002** [comment]
> I haven't thought about stamping much. let's split labels and stamping into their own PRs. I'd like to have a solid implementation for stamping and support config_setting at the same time.

Fair enough. Let me remove the stamping part.

**Review by alexeagle — APPROVED** [review]
nice, thanks!

**Review by thesayyn — APPROVED** [review]

**Comment by thesayyn** [comment]
looks like you need to run `bazel run //docs:update`

**Comment by psalaberria002** [comment]
> looks like you need to run `bazel run //docs:update`

Done.

**Comment by thesayyn** [comment]
Thanks!

**Pull request merged**
