### PR TITLE
Draft: feat: oci_bundle

### PR DESCRIPTION
**Pull request by hunshcn**
similar to crane pull --format=oci image1 image2 output-dir, but locally

Preparation of https://github.com/bazel-contrib/rules_oci/issues/248

( I create https://github.com/google/go-containerregistry/pull/1787 to support push bundle. )

but we should support bundle first.

### CODE REVIEW

**Comment by hunshcn** [comment]
use ln instead of cp, in https://github.com/bazel-contrib/rules_oci/pull/359

**Comment by hunshcn** [comment]
The conten of this pr has been completed, but I can't do codegen.

> bazel run //:gazelle

```plain
INFO: Analyzed target //:gazelle (2 packages loaded, 63 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/gazelle-runner.bash
  bazel-bin/gazelle
INFO: Elapsed time: 0.270s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/gazelle
grep: MANIFEST: No such file or directory
/root/.cache/bazel/_bazel_root/37ac864eff3240afc36de450593d425f/execroot/rules_oci/bazel-out/k8-fastbuild/bin/gazelle: warning: could not locate GOROOT used by rules_go
gazelle: /build/rules_oci/e2e/auth/BUILD.bazel: unknown directive: gazelle:prefix
```

any help?

**Comment by thesayyn** [comment]
Hey. thanks for the PR. we already have an oci_image_index rule that does basically what this does. About pushing to multiple repositories, you can always use multiple oci_push targets.  We will be happy to see the oci_push feature that supports pushing to multiple repositories efficiently.

**Comment by thesayyn** [comment]
Expanding the Public API is the last thing we want to do here. Please see our motivation behind this https://github.com/bazel-contrib/rules_oci#bazel-rules-for-oci-containers

**Comment by hunshcn** [comment]
In some offline deployment scenarios, we need to bundle all the images, copy them to the machine through mobile media, and then push them to registry through tools such as crane.

Do you think this should be a private rule because of low frequency of use?

**Comment by hunshcn** [comment]
I think it is reasonable to provide a similar ability to `crane pull multiimag...  bundle-dir  .

**Comment by thesayyn** [comment]
> Do you think this should be a private rule because of low frequency of use

Not really. I was implying that this should not go into rules_oci at all. Once it is in our public API, we are on the hook to maintain it forever.  Given that we are not trying to be a drop-in replacement for rules_docker it's less likely that we will have a rule similar to container_bundle.  I would recommend

**Comment by hunshcn** [comment]
move to https://github.com/hunshcn/rule_oci_bundle

**Pull request closed without merging**
