### PR TITLE
image: allow .tar.zst extension on layer tar

### LINKED ISSUE #519: Allow layers to take in files other than .tar and .tar.gz
We've been using bazel-lib tar to make layers for oci_images. It supports adding compress = "zstd".
It has actually been working fine and speeding up our builds quite a bit.
However, as I've updated bazel-lib, the generated tar file now has a .tar.zst extension instead of a .tar extension.
Only now do oci_images complain since they only accept .tar and .tar.gz files. 
I'm wondering if it should not already be allowed to take more than just those file extensions since it has been able to handle zstd compressed tars already.

### PR DESCRIPTION
**Pull request by alexeagle**
Fixes #519

### CODE REVIEW

**Review by thesayyn — APPROVED** [review]

**Comment by thesayyn** [comment]
We should have a test for this as well.

**Comment by thesayyn** [comment]
Coming back to this, i don't believe this works with crane.

**Comment by alexeagle** [comment]
do you think we should revert?

**Comment by thesayyn** [comment]
Yeah, until we can add some tests. https://github.com/bazel-contrib/rules_oci/issues/333

**Comment by alexeagle** [comment]
okay, reverted

**Pull request merged**
