### PR TITLE
fix: add cgr.dev into known www_authenticate schemes

### PR DESCRIPTION
**Pull request by tstromberg**
This is necessary on top of #237 for pulling authenticated images from cgr.dev (Chainguard Images). Without this patch, the following error occurs:

`Error in fail: Failed to fetch https://cgr.dev/v2/chainguard/static/manifests/latest curl: (22) The requested URL returned error: 401`

### CODE REVIEW

**Comment by thesayyn** [comment]
@tstromberg can you also add an oci_pull target fetching from cgr.dev to fetch.bzl and [oci/tests/BUILD.bazel](https://github.com/bazel-contrib/rules_oci/blob/675f05215ea61b2ac21c04349d13d9c82a3b7750/oci/tests/BUILD.bazel#L47-L59) so that we ensure it works?

**Comment by tstromberg** [comment]
Sounds good, I'll do that!

**Comment by thesayyn** [comment]
@tstromberg any luck adding the tests?

**Comment by tstromberg** [comment]
Ugh. I'm going to re-propose this PR from a clean fork.

**Pull request closed without merging**
