### PR TITLE
feat: implement tars symlinks

### PR DESCRIPTION
**Pull request by thesayyn**
fixes https://github.com/bazel-contrib/rules_oci/issues/508, needs https://github.com/bazel-contrib/rules_oci/pull/558 first.

### CODE REVIEW

**Comment by thesayyn** [comment]
@gregmagolan is case you are interested, this is the one that will make RBE go fast.

**Comment by mortenmj** [comment]
Seeing a lot of very similar errors when testing this one. At the surface, it looks like this broke all of our images that we pass tars to (built with pkg_tar in our case).

**Comment by thesayyn** [comment]
That is interesting, do you have more information on this? eg which service are you using?

**Comment by thesayyn** [comment]
This could be a Bazel bug!

**Review by alexeagle — APPROVED** [review]
Long journey to get here!

**Comment by mortenmj** [comment]
> That is interesting, do you have more information on this? eg which service are you using?

We use Buildbarn. As far as I can tell, from looking at what got scheduled remotely, this never hit the build cluster at all.

**Pull request merged**
