### PR TITLE
chore: remove structure test

### PR DESCRIPTION
**Pull request by alexeagle**
The rule should just live in the repo that provides the binaries. It has no coupling at all with the code in this repo, rather it should be coupled with the container-structure-test Go program.

I'm working with @loosebazooka to see if that might be accepted upstream, then we don't need to carry this in the rules_oci public api.

### CODE REVIEW

**Comment by thesayyn** [comment]
this is awesome.

**Comment by alexeagle** [comment]
We have a preliminary okay to upstream this, so I'm going to remove it before 1.0

**Comment by thesayyn** [comment]
> We have a preliminary okay to upstream this, so I'm going to remove it before 1.0

sounds good. lmk when it's ready for review

**Comment by alexeagle** [comment]
@thesayyn ready for a review. We have to decide if we want to land this before we get into the upstream, or are okay with aspect-forks.

**Comment by alexeagle** [comment]
upstream PR has landed, cleaning this up now.

**Review by thesayyn — APPROVED** [review]
🤩

**Pull request merged**
